import { boolean, integer, jsonb, pgEnum, pgTable, text, timestamp, uuid, unique } from "drizzle-orm/pg-core";

export const sessionStatus = pgEnum("session_status", ["LIVE", "ENDED", "PAUSED"]);
export const entitlementStatus = pgEnum("entitlement_status", ["CREATED", "AWAITING_QUESTION", "MODERATION", "QUEUED", "FULFILLING", "COMPLETED", "NEEDS_REPLACEMENT", "MANUAL_REVIEW", "CANCELLED"]);
export const requestStatus = pgEnum("request_status", ["RECEIVED", "MODERATION", "CARD_SELECTION", "GENERATING_TEXT", "VALIDATING_TEXT", "GENERATING_AUDIO", "READY", "PLAYING", "COMPLETED", "FAILED_RETRYABLE", "MANUAL_REVIEW"]);

const auditTimestamps = { createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow() };

export const liveSessions = pgTable("live_sessions", {
  id: uuid("id").primaryKey(), accountKey: text("account_key").notNull(), locale: text("locale").notNull(), status: sessionStatus("status").notNull(), startedAt: timestamp("started_at", { withTimezone: true }).notNull(), endedAt: timestamp("ended_at", { withTimezone: true })
});
export const users = pgTable("users", {
  id: uuid("id").primaryKey(), platform: text("platform").notNull(), platformUserId: text("platform_user_id").notNull(), username: text("username").notNull(), displayName: text("display_name").notNull(), firstSeenAt: timestamp("first_seen_at", { withTimezone: true }).notNull(), lastSeenAt: timestamp("last_seen_at", { withTimezone: true }).notNull()
}, (table) => ({ platformUserUnique: unique("users_platform_platform_user_id_unique").on(table.platform, table.platformUserId) }));
export const rawEvents = pgTable("raw_events", {
  id: uuid("id").primaryKey(), sessionId: uuid("session_id").notNull(), source: text("source").notNull(), externalId: text("external_id").notNull(), type: text("type").notNull(), payloadJson: jsonb("payload_json").notNull(), occurredAt: timestamp("occurred_at", { withTimezone: true }).notNull(), receivedAt: timestamp("received_at", { withTimezone: true }).notNull().defaultNow()
}, (table) => ({ sourceExternalUnique: unique("raw_events_source_external_id_unique").on(table.source, table.externalId) }));
export const comments = pgTable("comments", { id: uuid("id").primaryKey(), rawEventId: uuid("raw_event_id").notNull(), sessionId: uuid("session_id").notNull(), userId: uuid("user_id").notNull(), text: text("text").notNull(), occurredAt: timestamp("occurred_at", { withTimezone: true }).notNull(), ...auditTimestamps });
export const giftProducts = pgTable("gift_products", { id: uuid("id").primaryKey(), accountKey: text("account_key").notNull(), giftId: text("gift_id").notNull(), giftName: text("gift_name").notNull(), productCode: text("product_code").notNull(), cards: integer("cards").notNull(), priority: integer("priority").notNull(), questionRequired: boolean("question_required").notNull(), maxWords: integer("max_words").notNull(), maxAudioSeconds: integer("max_audio_seconds").notNull(), enabled: boolean("enabled").notNull() });
export const giftEvents = pgTable("gift_events", { id: uuid("id").primaryKey(), rawEventId: uuid("raw_event_id").notNull(), sessionId: uuid("session_id").notNull(), userId: uuid("user_id").notNull(), giftId: text("gift_id").notNull(), giftName: text("gift_name").notNull(), quantity: integer("quantity").notNull(), productId: uuid("product_id"), finalizedAt: timestamp("finalized_at", { withTimezone: true }) }, (table) => ({ rawEventUnique: unique("gift_events_raw_event_id_unique").on(table.rawEventId) }));
export const entitlements = pgTable("entitlements", { id: uuid("id").primaryKey(), giftEventId: uuid("gift_event_id").notNull(), userId: uuid("user_id").notNull(), productId: uuid("product_id").notNull(), status: entitlementStatus("status").notNull(), questionDeadline: timestamp("question_deadline", { withTimezone: true }), failureReason: text("failure_reason"), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(), completedAt: timestamp("completed_at", { withTimezone: true }) }, (table) => ({ giftEventUnique: unique("entitlements_gift_event_id_unique").on(table.giftEventId) }));
export const readingRequests = pgTable("reading_requests", { id: uuid("id").primaryKey(), entitlementId: uuid("entitlement_id"), sessionId: uuid("session_id").notNull(), userId: uuid("user_id").notNull(), displayName: text("display_name").notNull(), source: text("source").notNull(), question: text("question"), status: requestStatus("status").notNull(), priority: integer("priority").notNull(), queuedAt: timestamp("queued_at", { withTimezone: true }).notNull(), startedAt: timestamp("started_at", { withTimezone: true }), completedAt: timestamp("completed_at", { withTimezone: true }) }, (table) => ({ entitlementUnique: unique("reading_requests_entitlement_id_unique").on(table.entitlementId) }));
export const likeTotals = pgTable("like_totals", { id: uuid("id").primaryKey(), sessionId: uuid("session_id").notNull(), userId: uuid("user_id").notNull(), platformUserId: text("platform_user_id").notNull(), quantity: integer("quantity").notNull(), updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow() }, (table) => ({ viewerSessionUnique: unique("like_totals_session_platform_user_unique").on(table.sessionId,table.platformUserId) }));
export const freeReadingGrants = pgTable("free_reading_grants", { id: uuid("id").primaryKey(), sessionId: uuid("session_id").notNull(), userId: uuid("user_id").notNull(), platformUserId: text("platform_user_id").notNull(), requestId: uuid("request_id").notNull(), likeCount: integer("like_count").notNull(), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow() }, (table) => ({ viewerSessionUnique: unique("free_reading_grants_session_platform_user_unique").on(table.sessionId,table.platformUserId) }));
export const selectedCards = pgTable("selected_cards", { requestId: uuid("request_id").notNull(), position: integer("position").notNull(), cardId: text("card_id").notNull(), orientation: text("orientation").notNull(), seedHash: text("seed_hash").notNull() }, (table) => ({ requestPositionUnique: unique("selected_cards_request_position_unique").on(table.requestId, table.position) }));
export const readings = pgTable("readings", { id: uuid("id").primaryKey(), requestId: uuid("request_id").notNull(), locale: text("locale").notNull(), generatedJson: jsonb("generated_json").notNull(), spokenText: text("spoken_text").notNull(), safetyStatus: text("safety_status").notNull(), generatorName: text("generator_name").notNull(), ...auditTimestamps });
export const audioAssets = pgTable("audio_assets", { id: uuid("id").primaryKey(), readingId: uuid("reading_id").notNull(), provider: text("provider").notNull(), voice: text("voice").notNull(), contentHash: text("content_hash").notNull(), localPath: text("local_path").notNull(), durationMs: integer("duration_ms").notNull(), ...auditTimestamps }, (table) => ({ contentHashUnique: unique("audio_assets_content_hash_unique").on(table.contentHash) }));
export const playbackAttempts = pgTable("playback_attempts", { id: uuid("id").primaryKey(), requestId: uuid("request_id").notNull(), commandId: uuid("command_id").notNull(), status: text("status").notNull(), startedAt: timestamp("started_at", { withTimezone: true }), lastHeartbeatAt: timestamp("last_heartbeat_at", { withTimezone: true }), completedAt: timestamp("completed_at", { withTimezone: true }), error: text("error") });
export const operatorActions = pgTable("operator_actions", { id: uuid("id").primaryKey(), action: text("action").notNull(), requestId: uuid("request_id"), detailJson: jsonb("detail_json"), ...auditTimestamps });
export const outbox = pgTable("outbox", { id: uuid("id").primaryKey(), topic: text("topic").notNull(), aggregateId: uuid("aggregate_id").notNull(), payloadJson: jsonb("payload_json").notNull(), availableAt: timestamp("available_at", { withTimezone: true }).notNull().defaultNow(), publishedAt: timestamp("published_at", { withTimezone: true }), attempts: integer("attempts").notNull().default(0), lastError: text("last_error") });
export const systemEvents = pgTable("system_events", { id: uuid("id").primaryKey(), type: text("type").notNull(), payloadJson: jsonb("payload_json").notNull(), ...auditTimestamps });

export const schema = { liveSessions, users, rawEvents, comments, giftProducts, giftEvents, entitlements, readingRequests, likeTotals, freeReadingGrants, selectedCards, readings, audioAssets, playbackAttempts, operatorActions, outbox, systemEvents };
