export const entitlementStates = ["CREATED","AWAITING_QUESTION","MODERATION","QUEUED","FULFILLING","COMPLETED","NEEDS_REPLACEMENT","MANUAL_REVIEW","CANCELLED"] as const;
export type EntitlementState = typeof entitlementStates[number];
export const requestStates = ["RECEIVED","MODERATION","CARD_SELECTION","GENERATING_TEXT","VALIDATING_TEXT","GENERATING_AUDIO","READY","PLAYING","COMPLETED","FAILED_RETRYABLE","MANUAL_REVIEW"] as const;
export type RequestState = typeof requestStates[number];
const entitlementTransitions: Record<EntitlementState, EntitlementState[]> = { CREATED:["AWAITING_QUESTION","MODERATION","CANCELLED"], AWAITING_QUESTION:["MODERATION","CANCELLED"], MODERATION:["QUEUED","AWAITING_QUESTION","MANUAL_REVIEW"], QUEUED:["FULFILLING","MANUAL_REVIEW","CANCELLED"], FULFILLING:["COMPLETED","NEEDS_REPLACEMENT","MANUAL_REVIEW"], COMPLETED:[], NEEDS_REPLACEMENT:["QUEUED","CANCELLED"], MANUAL_REVIEW:["QUEUED","CANCELLED"], CANCELLED:[] };
const requestTransitions: Record<RequestState, RequestState[]> = { RECEIVED:["MODERATION","MANUAL_REVIEW"], MODERATION:["CARD_SELECTION","MANUAL_REVIEW","RECEIVED"], CARD_SELECTION:["GENERATING_TEXT","FAILED_RETRYABLE"], GENERATING_TEXT:["VALIDATING_TEXT","FAILED_RETRYABLE"], VALIDATING_TEXT:["GENERATING_AUDIO","FAILED_RETRYABLE","MANUAL_REVIEW"], GENERATING_AUDIO:["READY","FAILED_RETRYABLE"], READY:["PLAYING","FAILED_RETRYABLE"], PLAYING:["COMPLETED","FAILED_RETRYABLE","MANUAL_REVIEW"], COMPLETED:[], FAILED_RETRYABLE:["MODERATION","CARD_SELECTION","GENERATING_TEXT","GENERATING_AUDIO","MANUAL_REVIEW"], MANUAL_REVIEW:["MODERATION","CARD_SELECTION","COMPLETED"] };
export function canTransition(kind: "entitlement"|"request", from: string, to: string): boolean { if (kind === "entitlement") return (entitlementTransitions[from as EntitlementState] ?? []).includes(to as EntitlementState); return (requestTransitions[from as RequestState] ?? []).includes(to as RequestState); }
export function assertTransition(kind: "entitlement"|"request", from: string, to: string): void { if (!canTransition(kind, from, to)) throw new Error(`Invalid ${kind} transition: ${from} -> ${to}`); }
export const priorities = { replacement: 1000, elite: 400, premium: 300, standard: 200, quick: 100, free: 0 } as const;
export function compareQueue(a: { priority: number; queuedAt: number }, b: { priority: number; queuedAt: number }): number { return b.priority - a.priority || a.queuedAt - b.queuedAt; }

const unsafe = [
  [/\b(suicid|suicidarme|hacerme daño|matarme|autoles)/i, "self_harm"], [/\b(cuándo voy a morir|fecha de muerte|moriré)/i, "death_prediction"], [/\b(diag[nó]stico|medicina|medicamento|enfermedad|embaraz)/i, "medical_or_pregnancy"], [/\b(demanda|juicio|legal|cárcel|policía)/i, "legal_or_crime"], [/\b(invertir|apuesta|apostar|lotería|dinero seguro)/i, "investment_or_gambling"], [/\b(dirección|teléfono|doxx|doxing)/i, "doxxing"], [/\b(menor|niña|niño|sexo|sexual)/i, "minor_or_sexual"], [/\b(él piensa exactamente|ella piensa exactamente|me va a obedecer)/i, "guaranteed_third_party_action"]
] as const;
export function premoderate(question: string): { action: "ALLOW" } | { action: "REQUEST_NEW_QUESTION"; reasonCode: string } | { action: "REFRAME"; safeQuestion: string } { for (const [pattern, reasonCode] of unsafe) if (pattern.test(question)) return { action: "REQUEST_NEW_QUESTION", reasonCode }; return { action: "ALLOW" }; }
export function buildSafeFallback(question: string, cards: Array<{id:string; meaning:string}>): string { return `Esta lectura es para entretenimiento y reflexión personal sobre: ${question}. ${cards.map((c) => `${c.id}: ${c.meaning}`).join(" ")} Toma lo que te sirva y decide desde tu propio criterio.`; }
