import crypto from "node:crypto";
import { compareQueue, assertTransition, priorities, type EntitlementState, type RequestState } from "@tarot/domain";
import type { LiveEvent, LiveUser } from "@tarot/contracts";
import type { DurableRecovery } from "@tarot/db";

export type Product = { id:string; accountKey:string; giftId:string; giftName:string; productCode:string; cards:number; priority:number; questionRequired:boolean; maxWords:number; maxAudioSeconds:number; enabled:boolean };
export type Entitlement = { id:string; giftEventId:string; sessionId:string; userId:string; productId:string; status:EntitlementState; questionDeadline?:number; failureReason?:string; createdAt:number; completedAt?:number };
export type Request = { id:string; entitlementId?:string; sessionId:string; userId:string; source:"paid"|"free"; question?:string; safeQuestion?:string; status:RequestState; priority:number; queuedAt:number; startedAt?:number; completedAt?:number; displayName:string; cards?:Array<{id:string; orientation:"upright"|"reversed"; meaning:string}>; seedHash?:string; reading?:{id?:string; safe?:true; category?:string; opening?:string; cards:Array<{cardId:string; interpretation:string}>; summary?:string; closing?:string; spokenText:string; safetyFlags?:string[]}; audio?:{url:string; durationMs:number; contentHash?:string; localPath?:string; format?:"wav"|"mp3"} };
export type Session = { id:string; accountKey:string; locale:string; status:"LIVE"|"ENDED"|"PAUSED"; startedAt:number; endedAt?:number };
export type FreeGrant = { id:string; sessionId:string; userId:string; platformUserId:string; likeCount:number; createdAt:number };

function normalizedGiftName(value:string): string { return value.trim().replace(/\s+/g," ").toLocaleLowerCase(); }
function stableUuid(value:string): string { const hex=crypto.createHash("sha256").update(value).digest("hex").slice(0,32).split(""); hex[12]="5"; hex[16]=((parseInt(hex[16]!,16)&0x3)|0x8).toString(16); return `${hex.slice(0,8).join("")}-${hex.slice(8,12).join("")}-${hex.slice(12,16).join("")}-${hex.slice(16,20).join("")}-${hex.slice(20).join("")}`; }

const SEEDED_PRODUCTS = [
  {id:"0a77b9a9-8df7-5c1a-9cbd-f3c365a78011",giftId:"perfume",giftName:"Perfume",productCode:"quick",cards:1,priority:priorities.quick,questionRequired:true,maxWords:80,maxAudioSeconds:30},
  {id:"0a77b9a9-8df7-5c1a-9cbd-f3c365a78012",giftId:"hand-heart",giftName:"Hand Heart",productCode:"standard",cards:3,priority:priorities.standard,questionRequired:true,maxWords:180,maxAudioSeconds:75},
  {id:"0a77b9a9-8df7-5c1a-9cbd-f3c365a78013",giftId:"fairy-hide",giftName:"Fairy Hide",productCode:"premium",cards:5,priority:priorities.premium,questionRequired:true,maxWords:300,maxAudioSeconds:120},
  {id:"0a77b9a9-8df7-5c1a-9cbd-f3c365a78014",giftId:"face-pulling",giftName:"Face-pulling",productCode:"elite",cards:7,priority:priorities.elite,questionRequired:true,maxWords:420,maxAudioSeconds:165}
] as const;

export class MemoryStore {
  sessions = new Map<string, Session>(); users = new Map<string, LiveUser & {id:string}>(); rawEvents = new Map<string, LiveEvent>(); comments: Array<{sessionId:string; userId:string; text:string; occurredAt:number}> = []; products = new Map<string, Product>(); entitlements = new Map<string, Entitlement>(); requests = new Map<string, Request>(); likeTotals = new Map<string,number>(); freeGrants = new Map<string,FreeGrant>(); outbox: Array<{id:string; topic:string; aggregateId:string; payload:unknown; publishedAt?:number}> = []; actions: Array<{at:number; action:string; requestId?:string; detail?:unknown}> = []; rendererClients = new Set<any>(); rendererSequence = 0; currentRequestId?:string; pausedPlayback = false; intakePaused = false;
  constructor(public readonly accountKey = "demo-account", public readonly freeLikesThreshold=2_000, private readonly questionLookbackMs=300_000, private readonly awaitingQuestionMs=120_000) { this.seedProducts(); }
  restore(snapshot: DurableRecovery): void { this.sessions.clear(); this.users.clear(); this.comments = []; this.entitlements.clear(); this.requests.clear(); this.likeTotals.clear(); this.freeGrants.clear(); if(snapshot.products?.length) { this.products.clear(); for(const product of snapshot.products) this.products.set(product.giftId,product); } for (const session of snapshot.sessions) this.sessions.set(session.id, session); for (const user of snapshot.users) this.users.set(`tiktok:${user.platformUserId}`, { id: user.id, platformUserId: user.platformUserId, username: user.username, displayName: user.displayName }); this.comments = snapshot.comments.map((comment) => ({ sessionId: comment.sessionId, userId: comment.userId, text: comment.text, occurredAt: comment.occurredAt })); for (const entitlement of snapshot.entitlements) this.entitlements.set(entitlement.id, entitlement); for (const total of snapshot.likeTotals ?? []) this.likeTotals.set(this.viewerSessionKey(total.sessionId,total.platformUserId),total.quantity); for (const grant of snapshot.freeGrants ?? []) this.freeGrants.set(this.viewerSessionKey(grant.sessionId,grant.platformUserId),grant); for (const item of snapshot.requests) { const request: Request = { id: item.id, sessionId: item.sessionId, userId: item.userId, source: item.source, status: item.status, priority: item.priority, queuedAt: item.queuedAt, displayName: item.displayName }; if (item.entitlementId) request.entitlementId = item.entitlementId; if (item.question) request.question = item.question; if (item.startedAt !== undefined) request.startedAt = item.startedAt; if (item.completedAt !== undefined) request.completedAt = item.completedAt; if (item.seedHash) request.seedHash = item.seedHash; if (item.cards) request.cards = item.cards.map((card) => ({ ...card, meaning: "" })); if (item.reading) request.reading = item.reading; if (item.audio) { const format = item.audio.localPath.toLowerCase().endsWith(".mp3") ? "mp3" : "wav"; request.audio = { ...item.audio, format, url: `/audio/${item.audio.contentHash}.${format}` }; } if (request.status === "PLAYING") { request.status = "FAILED_RETRYABLE"; if (request.entitlementId) { const entitlement = this.entitlements.get(request.entitlementId); if (entitlement && ["FULFILLING", "QUEUED"].includes(entitlement.status)) entitlement.status = "NEEDS_REPLACEMENT"; } this.actions.push({ at: this.now(), action: "PLAYBACK_RECOVERED_AS_REPLACEMENT", requestId: request.id }); } this.requests.set(request.id, request); } }
  private seedProducts(): void { for (const item of SEEDED_PRODUCTS) this.products.set(item.giftId,{...item,accountKey:this.accountKey,enabled:true}); }
  now(): number { return Date.now(); }
  createSession(locale:string, id: string = crypto.randomUUID()): Session { const session = {id,accountKey:this.accountKey,locale,status:"LIVE" as const,startedAt:this.now()}; this.sessions.set(session.id,session); return session; }
  getOrCreateUser(user:LiveUser): string { const key = `tiktok:${user.platformUserId}`; const current = this.users.get(key); if (current) { current.username=user.username; current.displayName=user.displayName; return current.id; } const id=crypto.randomUUID(); this.users.set(key,{...user,id}); return id; }
  eligibleQuestion(sessionId:string,userId:string): {text:string}|undefined { const cutoff=this.now()-this.questionLookbackMs; const comment=[...this.comments].reverse().find((candidate)=>candidate.sessionId===sessionId&&candidate.userId===userId&&candidate.occurredAt>=cutoff); return comment ? {text:comment.text} : undefined; }
  pendingEntitlement(sessionId:string,userId:string): Entitlement|undefined { const now=this.now(); return [...this.entitlements.values()].filter((e)=>e.sessionId===sessionId&&e.userId===userId&&e.status==="AWAITING_QUESTION" && (e.questionDeadline ?? now)>=now).sort((a,b)=>a.createdAt-b.createdAt)[0]; }
  requestsFor(entitlementId:string): Request[] { return [...this.requests.values()].filter((r)=>r.entitlementId===entitlementId); }
  transitionEntitlement(id:string,to:EntitlementState,detail?:unknown): Entitlement { const item=this.entitlements.get(id)!; assertTransition("entitlement",item.status,to); item.status=to; if(to==="COMPLETED") item.completedAt=this.now(); this.actions.push({at:this.now(),action:`ENTITLEMENT_${to}`,detail}); return item; }
  transitionRequest(id:string,to:RequestState,detail?:unknown): Request { const item=this.requests.get(id)!; assertTransition("request",item.status,to); item.status=to; if(to==="PLAYING") item.startedAt=this.now(); if(to==="COMPLETED") item.completedAt=this.now(); this.actions.push({at:this.now(),action:`REQUEST_${to}`,requestId:id,detail}); return item; }
  queueRequest(request:Request): void { this.requests.set(request.id,request); }
  queue(): Request[] { return [...this.requests.values()].filter((r)=>r.status==="READY").sort(compareQueue); }
  reviewQueue(): Request[] { return [...this.requests.values()].filter((r)=>["FAILED_RETRYABLE","MANUAL_REVIEW"].includes(r.status)).sort(compareQueue); }
  private viewerSessionKey(sessionId:string,platformUserId:string):string { return `${sessionId}:${platformUserId}`; }
  ingest(event:LiveEvent): {duplicate:boolean; created?:Request; entitlement?:Entitlement; freeGrant?:FreeGrant; likeTotal?:number} { if (this.rawEvents.has(event.id)) return {duplicate:true}; this.rawEvents.set(event.id,event); const userId = "user" in event ? this.getOrCreateUser(event.user) : undefined; this.sessions.get(event.sessionId) ?? this.createSession("es-MX",event.sessionId); if(event.type==="COMMENT" && userId) { this.comments.push({sessionId:event.sessionId,userId,text:event.text,occurredAt:new Date(event.occurredAt).getTime()}); const pending=this.pendingEntitlement(event.sessionId,userId); if(pending) { const request=this.attachPaidQuestion(pending,event.text,userId,event.sessionId); return {duplicate:false,created:request,entitlement:pending}; } return {duplicate:false}; } if(event.type==="GIFT_COMPLETED" && userId && !this.intakePaused) return this.ingestGift(event,userId); if(event.type==="LIKE" && userId && !this.intakePaused) return this.ingestLike(event,userId); return {duplicate:false}; }
  private attachPaidQuestion(entitlement:Entitlement,question:string,userId:string,sessionId:string):Request { if(entitlement.status!=="AWAITING_QUESTION" && entitlement.status!=="CREATED") throw new Error("Entitlement is not ready for a question"); this.transitionEntitlement(entitlement.id,"MODERATION"); const product=[...this.products.values()].find((candidate)=>candidate.id===entitlement.productId); if(!product) throw new Error("Gift product is missing"); const existing=this.requestsFor(entitlement.id).find((request)=>request.status==="MANUAL_REVIEW"); if(existing) { existing.question=question; existing.safeQuestion=question; existing.queuedAt=this.now(); this.transitionRequest(existing.id,"MODERATION",{reason:"replacement_question"}); this.outbox.push({id:crypto.randomUUID(),topic:"reading.requested",aggregateId:existing.id,payload:{requestId:existing.id}}); return existing; } const request:Request={id:crypto.randomUUID(),entitlementId:entitlement.id,sessionId,userId,source:"paid",question,safeQuestion:question,status:"RECEIVED",priority:product.priority,queuedAt:this.now(),displayName:this.displayName(userId)}; this.queueRequest(request); this.outbox.push({id:crypto.randomUUID(),topic:"reading.requested",aggregateId:request.id,payload:{requestId:request.id}}); return request; }
  private displayName(userId:string):string { return [...this.users.values()].find((user)=>user.id===userId)?.displayName ?? "Viewer"; }
  private ingestGift(event:Extract<LiveEvent,{type:"GIFT_COMPLETED"}>,userId:string): {duplicate:boolean;created?:Request;entitlement?:Entitlement} { const incomingName=normalizedGiftName(event.giftName); const product=[...this.products.values()].find((candidate)=>candidate.enabled && normalizedGiftName(candidate.giftName)===incomingName) ?? this.products.get(event.giftId); if(!product?.enabled) return {duplicate:false}; const giftEventId=stableUuid(`${event.sessionId}:${event.id}:finalized-gift`); const existing=[...this.entitlements.values()].find((e)=>e.giftEventId===giftEventId); if(existing) return {duplicate:true,entitlement:existing}; const entitlement:Entitlement={id:crypto.randomUUID(),giftEventId,sessionId:event.sessionId,userId,productId:product.id,status:"CREATED",questionDeadline:this.now()+this.awaitingQuestionMs,createdAt:this.now()}; this.entitlements.set(entitlement.id,entitlement); const recent=this.eligibleQuestion(event.sessionId,userId); if(product.questionRequired && !recent) { this.transitionEntitlement(entitlement.id,"AWAITING_QUESTION"); return {duplicate:false,entitlement}; } const request=this.attachPaidQuestion(entitlement,recent?.text ?? "",userId,event.sessionId); return {duplicate:false,created:request,entitlement}; }
  private ingestLike(event:Extract<LiveEvent,{type:"LIKE"}>,userId:string): {duplicate:boolean;created?:Request;freeGrant?:FreeGrant;likeTotal:number} { const key=this.viewerSessionKey(event.sessionId,event.user.platformUserId); const likeTotal=(this.likeTotals.get(key) ?? 0)+event.quantity; this.likeTotals.set(key,likeTotal); if(likeTotal<this.freeLikesThreshold || this.freeGrants.has(key)) return {duplicate:false,likeTotal}; const grant:FreeGrant={id:crypto.randomUUID(),sessionId:event.sessionId,userId,platformUserId:event.user.platformUserId,likeCount:likeTotal,createdAt:this.now()}; this.freeGrants.set(key,grant); const recent=this.eligibleQuestion(event.sessionId,userId); const question=recent?.text ?? "¿Qué energía puedo observar y cómo puedo cuidarme hoy?"; const request:Request={id:crypto.randomUUID(),sessionId:event.sessionId,userId,source:"free",question,safeQuestion:question,status:"RECEIVED",priority:priorities.free,queuedAt:this.now(),displayName:this.displayName(userId)}; this.queueRequest(request); this.outbox.push({id:crypto.randomUUID(),topic:"reading.requested",aggregateId:request.id,payload:{requestId:request.id}}); this.actions.push({at:this.now(),action:"FREE_READING_GRANTED",requestId:request.id,detail:{likeTotal,threshold:this.freeLikesThreshold}}); return {duplicate:false,created:request,freeGrant:grant,likeTotal}; }
  expireAwaitingQuestions(now=this.now()): Entitlement[] { const expired=[...this.entitlements.values()].filter((item)=>item.status==="AWAITING_QUESTION" && item.questionDeadline!==undefined && item.questionDeadline<now); for(const item of expired) this.transitionEntitlement(item.id,"CANCELLED",{reason:"question_deadline_expired"}); return expired; }
  latestSession(): Session|undefined { return [...this.sessions.values()].sort((a,b)=>b.startedAt-a.startedAt)[0]; }
  currentRequest():Request|undefined { return this.currentRequestId ? this.requests.get(this.currentRequestId) : undefined; }
  broadcast(message:unknown):void { this.rendererSequence++; const payload = typeof message === "object" && message !== null ? message as Record<string, unknown> : { message }; for(const client of this.rendererClients) try { client.send(JSON.stringify({sequence:this.rendererSequence,...payload})); } catch { this.rendererClients.delete(client); } }
}
